	  <!-- path to avatar -->         <!-- avatar name -->
	    <option value="avatars/abstract.jpg">Abstract</option> 
	    <option value="avatars/alien_helmet.jpg">Alien Helmet</option> 
	    <option value="avatars/anglewings.jpg">Anglewings</option>
	    <option value="avatars/axe.jpg">Axe</option>
	    <option value="avatars/basket.jpg">Basket</option>
	    <option value="avatars/bass_fret.jpg">Bass</option>
	    <option value="avatars/animal_bear.jpg">Bear</option>
	    <option value="avatars/animal_bird.jpg">Bird</option>
	    <option value="avatars/hiro_bird2.jpg">Bird II</option>
	    <option value="avatars/hiro_bird2_neg.jpg">Bird II Negative</option>
	    <option value="avatars/hiro_bird.jpg">Bird III</option>
	    <option value="avatars/character_bonehead.jpg">Bonehead</option>
	    <option value="avatars/box_avatar.gif">Box Avatar</option>
	    <option value="avatars/animal_butterfly.jpg">Butterfly I</option>
	    <option value="avatars/butterfly2.jpg">Butterfly II</option>
	    <option value="avatars/butterfly3.jpg">Butterfly III</option>
	    <option value="avatars/animal_butterfly_neg.jpg">Butterfly Negative</option>
	    <option value="avatars/candle.jpg">Candle</option>
	    <option value="avatars/character_catafly.jpg">Catafly</option>
	    <option value="avatars/center.jpg">Center</option>
	    <option value="avatars/chi.gif">Chi</option>
	    <option value="avatars/character_cyclops.jpg">Cyclops</option>
	    <option value="avatars/darksword.jpg">Dark Sword</option>
	    <option value="avatars/dragon_eye.jpg">Dragon Eye</option>
	    <option value="avatars/animal_doggy.jpg">Doggy</option>
	    <option value="avatars/animal_doggy2.jpg">Doggy II</option>
	    <option value="avatars/hiro_dolphin.jpg">Dolphin</option>
	    <option value="avatars/hiro_dolphin_neg.jpg">Dolphin Negative</option>
	    <option value="avatars/animal_duck.jpg">Duck</option>
	    <option value="avatars/animal_eel.jpg">Eel</option>
	    <option value="avatars/eye.jpg">Eye</option>
	    <option value="avatars/eye2.jpg">Eye II</option>
	    <option value="avatars/eye_storm.jpg">Eye Storm</option>
	    <option value="avatars/flower.jpg">Flower</option>
	    <option value="avatars/flower2.jpg">Flower II</option>
	    <option value="avatars/flying.jpg">Flying</option>
	    <option value="avatars/funkyfish.jpg">Funky Fish</option>
	    <option value="avatars/hiro_giraff.jpg">Giraff</option>
	    <option value="avatars/hiro_giraff_neg.jpg">Giraff Negative</option>
	    <option value="avatars/gorilla_skull.jpg">Gorilla Skull</option>
	    <option value="avatars/half_planet.jpg">Half Planet</option>
	    <option value="avatars/hiro_horse.jpg">Horse</option>
	    <option value="avatars/hiro_horse_neg.jpg">Horse Negative</option>
	    <option value="avatars/hand_neg.jpg">Hand Negative</option>
	    <option value="avatars/kanji_for_peace.jpg">Kanji For Peace</option>
	    <option value="avatars/leaf.jpg">Leaf</option>
	    <option value="avatars/lightbulb.jpg">Lightbulb</option>
	    <option value="avatars/lightening.jpg">Lightening</option>
	    <option value="avatars/lighthouse.jpg">Lighthouse</option>
	    <option value="avatars/animal_lizard.jpg">Lizard</option>
	    <option value="avatars/mask.jpg">Mask</option>
	    <option value="avatars/metalbird.jpg">Metalbird</option>
	    <option value="avatars/animal_monkey.jpg">Monkey</option>
	    <option value="avatars/animal_monkey2.jpg">Monkey II</option>
	    <option value="avatars/moon.jpg">Moon</option>
	    <option value="avatars/octa_feathers.jpg">Octa Feathers</option>
	    <option value="avatars/aninal_peac.jpg">Peacock</option>
	    <option value="avatars/character_pinprick.jpg">Pinprick</option>
	    <option value="avatars/praying_hands.jpg">Praying Hands</option>
	    <option value="avatars/pyramid.jpg">Pyramid</option>
	    <option value="avatars/radar.jpg">Radar</option>
	    <option value="avatars/redcross.jpg">Redcross</option>
	    <option value="avatars/rocking_horse.jpg">Rocking Horse</option>
	    <option value="avatars/scifi_planet_probe.jpg">Scifi Planet Probe</option>
	    <option value="avatars/seabug1.jpg">Sea Bug</option>
	    <option value="avatars/seecreature.jpg">Sea Creature</option>
	    <option value="avatars/seahorse_animation.gif">Seahorse Animation</option>
	    <option value="avatars/animal_shark.jpg">Shark</option>
	    <option value="avatars/shape_barbed.jpg">Shape Barbed</option>
	    <option value="avatars/shapes_quad_feather.jpg">Shapes Quad Feather</option>
	    <option value="avatars/side_smile.jpg">Side Smile</option>
	    <option value="avatars/side_smile_b.jpg">Side Smile II</option>
	    <option value="avatars/character_space_monkey.jpg">Space Monkey</option>
	    <option value="avatars/Sphere_animated2.gif">Sphere Animated</option>
	    <option value="avatars/Sphere_animated_small_ neg2.gif">Sphere Animated II</option>
	    <option value="avatars/spherewall.gif">Sphere Wall</option>
	    <option value="avatars/spider.jpg">Spider</option>
	    <option value="avatars/stone_face.jpg">Stone Face</option>
	    <option value="avatars/stone_fish.jpg">Stone Fish</option>
	    <option value="avatars/scene_sunoverlake.jpg">Sun over Lake</option>
	    <option value="avatars/scene_sunovermountains.jpg">Sun over Mountains</option>
	    <option value="avatars/animal_swan.jpg">Swan</option>
	    <option value="avatars/shapes_swish.jpg">Swish</option>
	    <option value="avatars/shapes_taran.jpg">Taran</option>
	    <option value="avatars/techno_eye.jpg">Techno Eye</option>
	    <option value="avatars/animal_vultar.jpg">Vultar</option>
	    <option value="avatars/character_warrior.jpg">Warrior</option>
	    <option value="avatars/scenery_water_mountains.jpg">Water Mountains</option>
	    <option value="avatars/waveform.jpg">Waveform</option>
	    <option value="avatars/web.jpg">Web</option>
	    <option value="avatars/animal_whale.jpg">Whale</option>
	    <option value="avatars/white_face.jpg">White Face</option>
	    <option value="avatars/WINGS.jpg">Wings</option>
	    <option value="avatars/wings2.jpg">Wings II</option>
	    <option value="avatars/wired_shell.jpg">Wired Shell</option>